config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  resources :users do
    resources :general_shopping_list, only: [:index]
    resources :foods, only: %i[index create new destroy]
    resources :recipes do
      resources :recipe_foods, only: %i[create new destroy]
    end
    resources :public_recipes, only: [:index]
  end
  root 'public_recipes#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end

    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id
    can :read, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipe, through: :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :food
  has_many :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = current_user
    @foods = Food.where(user_id: current_user.id)
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.food.new(params.require(:food).permit(:name, :measurment_unit, :price))
    respond_to do |format|
      format.html do
        if @food.save
          redirect_to user_foods_path, notice: 'Food successfully created'
        else
          flash.now[:error] = 'Error: food could not be saved'
          render :new, locals: { food: @food }
        end
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to user_foods_path(current_user.id), notice: 'Food successfully deleted'
  end
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  def index
    @user = current_user
    @recipes = current_user.recipe

    total_items(@recipes)
    total_value(@recipes)
  end

  def total_items(recipes)
    @food = 0
    recipes.map do |recipe|
      0 unless recipe.foods.any?
      @food += recipe.foods.distinct.count(:id)
    end
    @food
  end

  def total_value(recipes)
    @value = 0
    recipes.each do |recipe|
      recipe.recipe_foods.each do |food|
        @value += food.food.price * food.quantity
      end
    end
    @value
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @user = current_user
    @recipes = Recipe.includes(:user).where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @foods = current_user.food
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new(params.require(:recipe_food).permit(:food_id, :quantity))
    respond_to do |format|
      format.html do
        if @recipe_food.save
          redirect_to [@recipe.user, @recipe], notice: 'Food added successfully'
        else
          flash.now[:error] = 'Error:  Food could not be added'
          render :new, locals: { recipe_food: @recipe_food }
        end
      end
    end
  end

  def destroy
    @user = current_user
    @recipe = RecipeFood.find(params[:id])
    @recipe.destroy
    flash[:success] = 'ingredient deleted successfully.'
    redirect_to user_recipe_path(@recipe.recipe_id)
  end

  private

  def update_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user = current_user
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def show
    @user = current_user
    @recipe = Recipe.find(params[:id])
    @foods = @recipe.recipe_foods.includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipe.new(params.require(:recipe).permit(:name, :preparation_time, :cooking_time,
                                                                     :description, :public))
    if @recipe.save
      flash.notice = 'Recipe was successfully created.'
      redirect_to user_recipes_path(@recipe.user)
    else
      flash.alert = 'Recipe was not created.'
      render :new
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(public: params[:public])
      flash[:success] = 'public status successfully updated'
    else
      flash[:error] = 'Error: could not update public status'
    end
    redirect_to user_recipe_path(@recipe)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy!
    flash[:success] = 'Recipe deleted!'
    redirect_to recipes_path, notice: 'Recipe successfully deleted'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  def index
    @user = current_user
    redirect_to user_foods_path(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shopping_lists_helper.rb
module GeneralShoppingListsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<%= link_to 'Add Food', new_user_food_path %>
<table>
  <tr>
    <th>Food</th>
    <th>Measurement unit</th>
    <th>Unit price</th>
    <th>Actions</th>
  </tr>
  <%@foods.each do |food|%>
  <%= render partial: "shared/foods", locals: { food: food } %>
  <% end %>
</table>
<%= link_to 'View Recipes', user_recipes_path %>

app/views/foods/new.html.erb
<h1>Add Food</h1>

<%= form_with url: user_foods_path, method: :post, local: true, scope: :food do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :measurement_unit %>
    <%= form.text_field :measurment_unit %>
  </div>
  <div>
    <%= form.label :unit_price %><br>
    <%= form.text_field :price %>
  </div>
  <%= form.submit %>
<% end %>

app/views/general_shopping_list/index.html.erb
<h1>Shopping List</h1>
<div class="recipe">
  <div class="recipeLeft">
    <h3>Amount of items to buy: <%= @food %></h3>
  </div>
  <div>
    <h3>Value of food needed: <%= @value %></h3>
  </div>
</div>
<table>
  <tr>
    <th>Food</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
  <%@recipes.each do |recipe|%>
  <%= render partial: "shared/shoppingItems", locals: { recipe: recipe } %>
  <% end %>
</table>

app/views/layouts/_header.html.erb
<%if user_signed_in? %>
  <nav >
  <%= link_to root_path do %>
    <div >
      <h1>My Recipe App</h1>
    </div>
  <%end%>
  <div>
    <%= link_to "View Foods", user_foods_path(@user) %>
    <%= link_to "View All Recipes", user_recipes_path(@user) %>
    <%= link_to "View Public Recipe", root_path %>
    <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
  </div>
  </nav>
  <h3><%= current_user.name %> </h3>
  <%else%>
  <nav>
     <h1>My Recipe App</h1>
  </nav>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodRecipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="page">
      <%= yield %>
    </div>    
  </body>
</html>

app/views/public_recipes/index.html.erb
<h1>Public Recipes</h1>
<%@recipes.each do |recipe|%>
<%= render partial: "shared/publicRecipes", locals: { recipe: recipe } %>
<% end %>
<%= link_to 'View your Food', user_foods_path(@user) %>

app/views/recipe_foods/new.html.erb
<h1>Add Ingrediants</h1>

<%= form_with url: user_recipe_recipe_foods_path, method: :post, local: true, scope: :recipe_food do |form| %>
  <div>
    <%= form.label :Food %><br>
    <%= form.select :food_id, @foods.collect { |food| [food.name, food.id] } %>
  </div>
  <div>
    <%= form.label :quantity %><br>
    <%= form.number_field :quantity, min: 0 %>
  </div>
  <%= form.submit %>
<% end %>

app/views/recipes/index.html.erb
  <%= link_to 'Add Recipe', new_user_recipe_path %>
  <%@recipes.each do |recipe|%>
  <%= render partial: "shared/recipe", locals: { recipe: recipe } %>
  <% end %>

app/views/recipes/new.html.erb
<h1>Add Recipe</h1>

<%= form_with url: user_recipes_path, method: :post, local: true, scope: :recipe do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :preparation_time %><br>
    <%= form.text_field :preparation_time %>
  </div>
  <div>
    <%= form.label :cooking_time %><br>
    <%= form.text_field :cooking_time %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :public, "Public" %>
    <%= form.check_box :public %>
  </div>
  <%= form.submit %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name%></h1>
<div class="recipe">
  <div class="recipeLeft">
    <h3>Prepration Time: <%= @recipe.preparation_time%> Hour/s</h3>
    <h3>Cooking Time: <%= @recipe.cooking_time%> Hour/s</h3>
    <h3><%= @recipe.description%></h3>
  </div>
  <div>
    <% if can? :manage, @recipe%>
      <%= form_with url: user_recipe_path(@recipe), method: "put" do |form| %>
          <% if @recipe.public == false %>
            <%= form.check_box :public, id:"publicCheck", onchange: "this.form.submit();"%>
            <label for="publicCheck">Public</label>
          <% else %>
            <%= form.check_box :public, id:"publicCheck", checked: true, onchange: "this.form.submit();" %>
            <label for="publicCheck">Public</label>
          <%end%>
      <%end%> 
    <%end%>
  </div>
</div>
<div class="recipe">
  <%= link_to 'Add ingredient', new_user_recipe_recipe_food_path(@user, @recipe) %>
        <%= link_to 'Generate shopping list', user_general_shopping_list_index_path(current_user.id) %>
</div>
<hr>
<table>
  <tr>
    <th>Food</th>
    <th>Quantity</th>
    <th>Value</th>
    <th>Actions</th>
  </tr>
  <%@foods.each do |food|%>
  <%= render partial: "shared/ingrediants", locals: { food: food } %>
  <%end%>
</table>

app/views/shared/_foods.html.erb
<tr>
  <td><%=food.name%></td>
  <td><%=food.measurment_unit%></td>
  <td><%=food.price%></td>
  <td>
    <% if can? :destroy, food %> 
        <%= button_to 'Delete', user_food_path(@user.id, food.id), method: :delete %>    
    <% end %>
  </td>
</tr>

app/views/shared/_ingrediants.html.erb
<tr>
  <td><%=food.food.name%></td>
  <td><%=food.food.measurment_unit%></td>
  <td><%=food.food.price%></td>
  <td>
    <% if can? :manage, @recipe %> 
        <%= button_to 'Delete', user_recipe_recipe_food_path(user_id: @user.id, recipe_id: @recipe.id, id: food.id), method: :delete %>    
    <% end %>
  </td>
</tr>

app/views/shared/_publicRecipes.html.erb
<div class="flex">
  <div class="recipeLeft">
    <h2><%=link_to recipe.name, user_recipe_path(user_id: @user.id, id: recipe.id)%></h2>
    <p>By: <%= recipe.user.name %></p>
  </div>
  <div>
    <h3>Total Food items: <%= recipe.foods.distinct.count(:id)%></h3>
    <h3>Total Price: <%= recipe.foods.sum ('quantity * price') %></h3>
  </div>
</div>

app/views/shared/_recipe.html.erb
<div class="recipe">
  <div class="recipeLeft">
    <h2><%= link_to recipe.name, user_recipe_path(@user.id, recipe.id) %></h2>
    <%= button_to "Remove", user_recipe_path(@user.id, recipe.id), :method => :delete %>
  </div>
  <div>
    <p>
      <%= recipe.description %>
    </p>
  </div>
</div>

app/views/shared/_shoppingItems.html.erb
<%recipe.recipe_foods.each do |item|%>
  <tr>
    <td><%= item.food.name%></td>
    <td><%= item.quantity%></td>
    <td><%= item.food.price * item.quantity%></td>      
  </tr>
<%end%>

app/views/users/index.html.erb
<h2>Welcome <%= @user.name %></h2>